[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/2.3.x/*"
  to = "/latest/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/latest/getting_started/*"
  to = "/2.3.x/getting-started/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/latest/how_tos/*"
  to = "/2.3.x/how-tos/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/latest/deploy_manage/*"
  to = "/2.3.x/deploy_manage/:splat"
  status = 301
  force = true
